themes/default/routes/admin.php
<?php
App::booted(function() {
	$namespace = 'Sudo\Theme\Http\Controllers\Admin';
	Route::namespace($namespace)->name('admin.')->prefix(config('app.admin_dir'))->middleware(['web', 'auth-admin'])->group(function() {
		// route chung cho cấu hình
		Route::name('settings.')->prefix('settings')->group(function() {
			// Cấu hình chung
			Route::match(['GET', 'POST'], 'general', 'SettingController@general')->name('general');
			// Cấu hình trang chủ
			Route::match(['GET', 'POST'], 'home', 'SettingController@home')->name('home');
			// Cấu hình SEO
			Route::match(['GET', 'POST'], 'seo', 'SettingController@seo')->name('seo');
		});
	});
});

themes/default/routes/web.php
<?php
App::booted(function() {

	$namespace = 'Sudo\Theme\Http\Controllers\Web';
	Route::namespace($namespace)->name('app.')->middleware(['web'])->group(function() {

		Route::get('/test', 'TestController@index')->name('test');

		// Trang chủ
		Route::get('/', 'HomeController@index')->name('home');

		// Trang đơn
		Route::get('/page/{slug}.html', 'PageController@show')->name('pages.show');

		// Tin tức
		Route::get('/blog/{slug}.html', 'PostController@show')->name('posts.show');

		// Danh mục tin tức
		Route::get('/blog/{slug?}', 'PostController@index')->name('post_categories.index');

	});

});

themes/default/resources/views/admin/settings/form.blade.php
@extends('Core::layouts.app')

@section('title') @lang($title ?? 'Setting::general.title')  @endsection
@section('content')

<form action="" class="form-horizontal" enctype="multipart/form-data" method="post">
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<div class="card-title">@lang($note ?? 'Form::form.require_text')</div>
				<div class="card-tools">
					<button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
				</div>
			</div>
			<div class="card-body">
				@include('Form::generate')
			</div>
		</div>
	</div>
</div>
</form>

@endsection

themes/default/resources/views/general/layouts/adminbar.blade.php
@if(Auth::guard('admin')->check())
    <div class="adminbar">
    	<style type="text/css">.adminbar {width: 100%;float: left;clear: both;background: #252627;color: #fff;font-family: 'arial', 'Sans-serif';}.adminbar-wrap {padding: 0 10px;}.adminbar-wrap ul {list-style: none;}.adminbar-wrap ul li {font-size: 13px;line-height: 32px;float: left;margin-right: 20px;font-weight: bold;}.adminbar-wrap ul li a {display: block;color: #ffffff;text-decoration: none;}</style>
    	<div class="container wrap adminbar-wrap">
	    	<ul>
	    		<li><a href="{!!route('admin.home')!!}">@lang('Trang quản trị')</a></li>
	    		{{--truyền link edit nội dung vào biến view có tên $admin_bar--}}
	    		@if(isset($admin_bar) && $admin_bar != '')
	    			<li><a href="{!!$admin_bar!!}">&#9998; @lang('Sửa nội dung này')</a></li>
	            @endif
	    	</ul>
    	</div>
    </div>
@endif

themes/default/resources/views/general/layouts/seo.blade.php
{{-- 
	title: Lấy theo title tại biến MetaSeo
	Tiêu đề của trang
--}}
	<title>{{ $meta_seo['title'] ?? '' }}</title>
	
{{-- 
	description: Lấy theo description tại biến MetaSeo
	Mô tả của trang
--}}
@if(!empty($meta_seo['description']))
	<meta name="description" content="{{ $meta_seo['description'] ?? '' }}"/>
@endif

{{-- 
	robots: Lấy theo robots tại biến MetaSeo 
	có cho phép Google đánh index hay không
--}}
@if (isset($config_seo['robots']) && $config_seo['robots'] == '0')
	<meta name="robots" content="noindex,nofollow"/>
@elseif(isset($meta_seo['robots']) && !empty($meta_seo['robots']))
	<meta name="robots" content="{{ $meta_seo['robots'] ?? '' }}"/>
@endif

{{-- 
	canonical: Lấy theo url tại biến MetaSeo
	Dùng để định danh trang là duy nhất tại Domain
--}}
@if(!empty($meta_seo['url']))
	<link rel="canonical" href="{{ $meta_seo['url'] }}" />
@endif

{{-- 
	hreflang với website đa ngôn ngữ 
	$switch_language = [
		'lang_key_1' => 'lang_link_1',
		'lang_key_2' => 'lang_link_2',
	];
--}}
@if (isset($switch_language) && !empty($switch_language))
	@foreach ($switch_language as $lang_key => $lang_link)
		<link rel="alternate" hreflang="{{ $lang_key ?? '' }}" href="{{ $lang_link ?? '' }}">
	@endforeach
@endif

{{-- Facebook Meta Tags --}}
@if (!empty($meta_seo['locale']))
	<meta property="og:locale" content="{{ $meta_seo['locale'] }}" />
@endif
	<meta property="og:site_name" content="{{ config('app.name') }}" />
	<meta property="og:type" content="{{ $meta_seo['type'] ?? 'website' }}" />
@if(!empty($meta_seo['title']))
	<meta property="og:title" content="{{ $meta_seo['title'] ?? '' }}" />
@endif
@if(!empty($meta_seo['description']))
	<meta property="og:description" content="{{ $meta_seo['description'] }}" />
@endif
@if(!empty($meta_seo['url']))
	<meta property="og:url" content="{{ $meta_seo['url'] }}" />
@endif
@if(!empty($meta_seo['image']))
	<meta property="og:image" content="{{ $meta_seo['image'] }}" />
@endif

{{-- Twitter Meta Tags --}}
	<meta name="twitter:card" content="summary_large_image">
@if(!empty($meta_seo['title']))
	<meta name="twitter:title" content="{{ $meta_seo['title'] }}">
@endif
@if(!empty($meta_seo['description']))
	<meta name="twitter:description" content="{{ $meta_seo['description'] }}">
@endif
@if(!empty($meta_seo['image']))
	<meta name="twitter:image" content="{{ $meta_seo['image'] }}" />
@endif

themes/default/resources/views/web/home.blade.php
@extends('Default::web.layouts.app')

@section('content')

<h1 style="float: left; padding: 30px;">Welcome!</h1>

@endsection

themes/default/resources/views/web/layouts/app.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="vi" xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"/>
    <link href="{{ asset('favicon.ico') }}" type="image/x-icon" rel="shortcut icon"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="agent" content="{{ checkAgent() }}">
    {{-- Các meta seo --}}
    @include('Default::general.layouts.seo')
    {{-- Cấu hình Asset --}}
    {!! Asset::renderHeader() !!}
</head>
<body>
	{{-- Thanh admin hiển thị cho quản trị --}}
    @include('Default::general.layouts.adminbar')
	{{-- Nội dung trang --}}
    @yield('content')
    {{-- Cấu hình Asset --}}
    {!! Asset::renderFooter() !!}
</body>
</html>